# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\DEV\Freeporter\Views\UI_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 854)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout.addWidget(self.label_27)
        self.ActivesFolderLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ActivesFolderLineEdit.setObjectName("ActivesFolderLineEdit")
        self.horizontalLayout.addWidget(self.ActivesFolderLineEdit)
        self.selectActivesFolderButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectActivesFolderButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectActivesFolderButton.setObjectName("selectActivesFolderButton")
        self.horizontalLayout.addWidget(self.selectActivesFolderButton)
        self.includeActivesSubfolderCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.includeActivesSubfolderCheckbox.setObjectName("includeActivesSubfolderCheckbox")
        self.horizontalLayout.addWidget(self.includeActivesSubfolderCheckbox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_2.addWidget(self.label_28)
        self.PassivesFolderLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PassivesFolderLineEdit.setEnabled(True)
        self.PassivesFolderLineEdit.setObjectName("PassivesFolderLineEdit")
        self.horizontalLayout_2.addWidget(self.PassivesFolderLineEdit)
        self.selectPassivesFolderButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectPassivesFolderButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectPassivesFolderButton.setObjectName("selectPassivesFolderButton")
        self.horizontalLayout_2.addWidget(self.selectPassivesFolderButton)
        self.includePassivesSubfolderCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.includePassivesSubfolderCheckbox.setObjectName("includePassivesSubfolderCheckbox")
        self.horizontalLayout_2.addWidget(self.includePassivesSubfolderCheckbox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.AllYearsButton = QtWidgets.QPushButton(self.centralwidget)
        self.AllYearsButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.AllYearsButton.setObjectName("AllYearsButton")
        self.horizontalLayout_4.addWidget(self.AllYearsButton)
        self.NoneYearsButton = QtWidgets.QPushButton(self.centralwidget)
        self.NoneYearsButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.NoneYearsButton.setObjectName("NoneYearsButton")
        self.horizontalLayout_4.addWidget(self.NoneYearsButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.yearListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.yearListWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.yearListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.yearListWidget.setObjectName("yearListWidget")
        item = QtWidgets.QListWidgetItem()
        self.yearListWidget.addItem(item)
        self.verticalLayout_6.addWidget(self.yearListWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.AllMonthsButton = QtWidgets.QPushButton(self.centralwidget)
        self.AllMonthsButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.AllMonthsButton.setObjectName("AllMonthsButton")
        self.horizontalLayout_5.addWidget(self.AllMonthsButton)
        self.NoneMonthsButton = QtWidgets.QPushButton(self.centralwidget)
        self.NoneMonthsButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.NoneMonthsButton.setObjectName("NoneMonthsButton")
        self.horizontalLayout_5.addWidget(self.NoneMonthsButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.monthListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.monthListWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.monthListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.monthListWidget.setObjectName("monthListWidget")
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.monthListWidget.addItem(item)
        self.verticalLayout_7.addWidget(self.monthListWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.allActiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.allActiveButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.allActiveButton.setObjectName("allActiveButton")
        self.horizontalLayout_6.addWidget(self.allActiveButton)
        self.NoneActiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.NoneActiveButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.NoneActiveButton.setObjectName("NoneActiveButton")
        self.horizontalLayout_6.addWidget(self.NoneActiveButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.activesListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.activesListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.activesListWidget.setObjectName("activesListWidget")
        item = QtWidgets.QListWidgetItem()
        self.activesListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.activesListWidget.addItem(item)
        self.verticalLayout_5.addWidget(self.activesListWidget)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_18.setAcceptDrops(False)
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_7.addWidget(self.lineEdit_18)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_7.addWidget(self.label_23)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_17.setAcceptDrops(False)
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_7.addWidget(self.lineEdit_17)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_7.addWidget(self.label_24)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setAcceptDrops(False)
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_7.addWidget(self.lineEdit_16)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_8.addWidget(self.lineEdit_2)
        self.AllPassiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.AllPassiveButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.AllPassiveButton.setObjectName("AllPassiveButton")
        self.horizontalLayout_8.addWidget(self.AllPassiveButton)
        self.NonePassiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.NonePassiveButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.NonePassiveButton.setObjectName("NonePassiveButton")
        self.horizontalLayout_8.addWidget(self.NonePassiveButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.passivesListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.passivesListWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.passivesListWidget.setAlternatingRowColors(False)
        self.passivesListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.passivesListWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.passivesListWidget.setObjectName("passivesListWidget")
        item = QtWidgets.QListWidgetItem()
        self.passivesListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.passivesListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.passivesListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.passivesListWidget.addItem(item)
        self.verticalLayout_3.addWidget(self.passivesListWidget)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_20.setAcceptDrops(False)
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_9.addWidget(self.lineEdit_20)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_9.addWidget(self.label_25)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_21.setAcceptDrops(False)
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_9.addWidget(self.lineEdit_21)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_9.addWidget(self.label_26)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_19.setAcceptDrops(False)
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_9.addWidget(self.lineEdit_19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.netRevenueLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.netRevenueLineEdit.setAcceptDrops(False)
        self.netRevenueLineEdit.setReadOnly(True)
        self.netRevenueLineEdit.setObjectName("netRevenueLineEdit")
        self.gridLayout.addWidget(self.netRevenueLineEdit, 18, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 18, 1, 1, 1)
        self.totalExpensesGstPstLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalExpensesGstPstLineEdit.setAcceptDrops(False)
        self.totalExpensesGstPstLineEdit.setReadOnly(True)
        self.totalExpensesGstPstLineEdit.setObjectName("totalExpensesGstPstLineEdit")
        self.gridLayout.addWidget(self.totalExpensesGstPstLineEdit, 11, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 15, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 14, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 16, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 17, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 12, 1, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 5, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.totalDuesLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalDuesLineEdit.setAcceptDrops(False)
        self.totalDuesLineEdit.setReadOnly(True)
        self.totalDuesLineEdit.setObjectName("totalDuesLineEdit")
        self.gridLayout.addWidget(self.totalDuesLineEdit, 17, 2, 1, 1)
        self.provincialDuesLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.provincialDuesLineEdit.setAcceptDrops(False)
        self.provincialDuesLineEdit.setReadOnly(True)
        self.provincialDuesLineEdit.setObjectName("provincialDuesLineEdit")
        self.gridLayout.addWidget(self.provincialDuesLineEdit, 16, 2, 1, 1)
        self.federalDuesLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.federalDuesLineEdit.setAcceptDrops(False)
        self.federalDuesLineEdit.setReadOnly(True)
        self.federalDuesLineEdit.setObjectName("federalDuesLineEdit")
        self.gridLayout.addWidget(self.federalDuesLineEdit, 15, 2, 1, 1)
        self.grossRevenueLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.grossRevenueLineEdit.setAcceptDrops(False)
        self.grossRevenueLineEdit.setReadOnly(True)
        self.grossRevenueLineEdit.setObjectName("grossRevenueLineEdit")
        self.gridLayout.addWidget(self.grossRevenueLineEdit, 14, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 1, 1, 1)
        self.totalIncomeLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalIncomeLineEdit.setAcceptDrops(False)
        self.totalIncomeLineEdit.setAutoFillBackground(False)
        self.totalIncomeLineEdit.setReadOnly(True)
        self.totalIncomeLineEdit.setObjectName("totalIncomeLineEdit")
        self.gridLayout.addWidget(self.totalIncomeLineEdit, 1, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 13, 1, 1, 2)
        self.totalIncomeGstLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalIncomeGstLineEdit.setAcceptDrops(False)
        self.totalIncomeGstLineEdit.setReadOnly(True)
        self.totalIncomeGstLineEdit.setObjectName("totalIncomeGstLineEdit")
        self.gridLayout.addWidget(self.totalIncomeGstLineEdit, 3, 2, 1, 1)
        self.totalExpensesLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalExpensesLineEdit.setAcceptDrops(False)
        self.totalExpensesLineEdit.setReadOnly(True)
        self.totalExpensesLineEdit.setObjectName("totalExpensesLineEdit")
        self.gridLayout.addWidget(self.totalExpensesLineEdit, 8, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 11, 1, 1, 1)
        self.totalExpensesGstLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalExpensesGstLineEdit.setAcceptDrops(False)
        self.totalExpensesGstLineEdit.setReadOnly(True)
        self.totalExpensesGstLineEdit.setObjectName("totalExpensesGstLineEdit")
        self.gridLayout.addWidget(self.totalExpensesGstLineEdit, 10, 2, 1, 1)
        self.totalIncomePstLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalIncomePstLineEdit.setAcceptDrops(False)
        self.totalIncomePstLineEdit.setReadOnly(True)
        self.totalIncomePstLineEdit.setObjectName("totalIncomePstLineEdit")
        self.gridLayout.addWidget(self.totalIncomePstLineEdit, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 10, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 9, 1, 1, 1)
        self.totalIncomeGstPstLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalIncomeGstPstLineEdit.setAcceptDrops(False)
        self.totalIncomeGstPstLineEdit.setReadOnly(True)
        self.totalIncomeGstPstLineEdit.setObjectName("totalIncomeGstPstLineEdit")
        self.gridLayout.addWidget(self.totalIncomeGstPstLineEdit, 4, 2, 1, 1)
        self.totalExpensesPstLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalExpensesPstLineEdit.setAcceptDrops(False)
        self.totalExpensesPstLineEdit.setReadOnly(True)
        self.totalExpensesPstLineEdit.setObjectName("totalExpensesPstLineEdit")
        self.gridLayout.addWidget(self.totalExpensesPstLineEdit, 9, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 19, 1, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 2)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1091, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionaaa = QtWidgets.QAction(MainWindow)
        self.actionaaa.setObjectName("actionaaa")
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionaaa)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.yearListWidget.itemSelectionChanged.connect(MainWindow.select_years)
        self.monthListWidget.itemSelectionChanged.connect(MainWindow.select_months)
        self.activesListWidget.itemSelectionChanged.connect(MainWindow.select_actives)
        self.passivesListWidget.itemSelectionChanged.connect(MainWindow.select_passives)
        self.AllYearsButton.clicked.connect(MainWindow.select_all_years)
        self.NoneYearsButton.clicked.connect(MainWindow.select_none_years)
        self.AllMonthsButton.clicked.connect(MainWindow.select_all_months)
        self.NoneMonthsButton.clicked.connect(MainWindow.select_none_months)
        self.allActiveButton.clicked.connect(MainWindow.select_all_actives)
        self.NoneActiveButton.clicked.connect(MainWindow.select_none_actives)
        self.AllPassiveButton.clicked.connect(MainWindow.select_all_passives)
        self.NonePassiveButton.clicked.connect(MainWindow.select_none_passives)
        self.selectActivesFolderButton.clicked.connect(MainWindow.open_actives_folder_selection_dialog)
        self.selectPassivesFolderButton.clicked.connect(MainWindow.open_passives_folder_selection_dialog)
        self.includeActivesSubfolderCheckbox.stateChanged['int'].connect(MainWindow.include_actives_subfolders)
        self.includePassivesSubfolderCheckbox.stateChanged['int'].connect(MainWindow.include_passives_subfolders)
        self.ActivesFolderLineEdit.textChanged['QString'].connect(MainWindow.select_actives_folder)
        self.PassivesFolderLineEdit.textChanged['QString'].connect(MainWindow.select_passives_folder)
        self.lineEdit.textChanged['QString'].connect(MainWindow.filter_actives)
        self.lineEdit_2.textChanged['QString'].connect(MainWindow.filter_passives)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_27.setText(_translate("MainWindow", "Actives folder"))
        self.selectActivesFolderButton.setText(_translate("MainWindow", "Browse"))
        self.includeActivesSubfolderCheckbox.setText(_translate("MainWindow", "Include subfolders"))
        self.label_28.setText(_translate("MainWindow", "Passives folder"))
        self.selectPassivesFolderButton.setText(_translate("MainWindow", "Browse"))
        self.includePassivesSubfolderCheckbox.setText(_translate("MainWindow", "Include subfolders"))
        self.label_21.setText(_translate("MainWindow", "Year"))
        self.AllYearsButton.setText(_translate("MainWindow", "All"))
        self.NoneYearsButton.setText(_translate("MainWindow", "None"))
        __sortingEnabled = self.yearListWidget.isSortingEnabled()
        self.yearListWidget.setSortingEnabled(False)
        item = self.yearListWidget.item(0)
        item.setText(_translate("MainWindow", "2018"))
        self.yearListWidget.setSortingEnabled(__sortingEnabled)
        self.label_22.setText(_translate("MainWindow", "Month"))
        self.AllMonthsButton.setText(_translate("MainWindow", "All"))
        self.NoneMonthsButton.setText(_translate("MainWindow", "None"))
        __sortingEnabled = self.monthListWidget.isSortingEnabled()
        self.monthListWidget.setSortingEnabled(False)
        item = self.monthListWidget.item(0)
        item.setText(_translate("MainWindow", "January"))
        item = self.monthListWidget.item(1)
        item.setText(_translate("MainWindow", "February"))
        item = self.monthListWidget.item(2)
        item.setText(_translate("MainWindow", "March"))
        item = self.monthListWidget.item(3)
        item.setText(_translate("MainWindow", "April"))
        item = self.monthListWidget.item(4)
        item.setText(_translate("MainWindow", "May"))
        item = self.monthListWidget.item(5)
        item.setText(_translate("MainWindow", "June"))
        item = self.monthListWidget.item(6)
        item.setText(_translate("MainWindow", "Juillet"))
        item = self.monthListWidget.item(7)
        item.setText(_translate("MainWindow", "August"))
        item = self.monthListWidget.item(8)
        item.setText(_translate("MainWindow", "September"))
        item = self.monthListWidget.item(9)
        item.setText(_translate("MainWindow", "October"))
        item = self.monthListWidget.item(10)
        item.setText(_translate("MainWindow", "November"))
        item = self.monthListWidget.item(11)
        item.setText(_translate("MainWindow", "December"))
        self.monthListWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Active"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Type to filter"))
        self.allActiveButton.setText(_translate("MainWindow", "All"))
        self.NoneActiveButton.setText(_translate("MainWindow", "None"))
        __sortingEnabled = self.activesListWidget.isSortingEnabled()
        self.activesListWidget.setSortingEnabled(False)
        item = self.activesListWidget.item(0)
        item.setText(_translate("MainWindow", "ATW December"))
        item = self.activesListWidget.item(1)
        item.setText(_translate("MainWindow", "Kinessor November"))
        self.activesListWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Total"))
        self.label_23.setText(_translate("MainWindow", "GST"))
        self.label_24.setText(_translate("MainWindow", "PST"))
        self.label_4.setText(_translate("MainWindow", "Passive"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Type to filter"))
        self.AllPassiveButton.setText(_translate("MainWindow", "All"))
        self.NonePassiveButton.setText(_translate("MainWindow", "None"))
        __sortingEnabled = self.passivesListWidget.isSortingEnabled()
        self.passivesListWidget.setSortingEnabled(False)
        item = self.passivesListWidget.item(0)
        item.setText(_translate("MainWindow", "Cell phone"))
        item = self.passivesListWidget.item(1)
        item.setText(_translate("MainWindow", "Resistors"))
        item = self.passivesListWidget.item(2)
        item.setText(_translate("MainWindow", "Drone"))
        item = self.passivesListWidget.item(3)
        item.setText(_translate("MainWindow", "Bulletproof tires"))
        self.passivesListWidget.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "Total"))
        self.label_25.setText(_translate("MainWindow", "GST"))
        self.label_26.setText(_translate("MainWindow", "PST"))
        self.label_20.setText(_translate("MainWindow", "Net revenue"))
        self.label_17.setText(_translate("MainWindow", "Federal dues"))
        self.label_16.setText(_translate("MainWindow", "Gross revenue"))
        self.label_18.setText(_translate("MainWindow", "Provincial dues"))
        self.label_19.setText(_translate("MainWindow", "Total dues"))
        self.label_6.setText(_translate("MainWindow", "Amount"))
        self.label_11.setText(_translate("MainWindow", "Amount"))
        self.label_15.setText(_translate("MainWindow", "DECLARABLE REVENUE"))
        self.label_14.setText(_translate("MainWindow", "PST + GST"))
        self.label_7.setText(_translate("MainWindow", "PST + GST"))
        self.label_13.setText(_translate("MainWindow", "GST"))
        self.label_12.setText(_translate("MainWindow", "PST"))
        self.label_9.setText(_translate("MainWindow", "EXPENSES"))
        self.label_5.setText(_translate("MainWindow", "INCOME"))
        self.label_8.setText(_translate("MainWindow", "PST"))
        self.label_10.setText(_translate("MainWindow", "GST"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionaaa.setText(_translate("MainWindow", "aaa"))

